config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root 'static_pages#home'
  get  '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :posts, only: [:new, :create, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_digest
  before_create :create_remember_token
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :posts

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(string)
    Digest::SHA1.hexdigest(string.to_s)
  end

  def create_remember_token
    self.remember_token = User.digest(User.new_token)
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signin, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Post successfully submitted!"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all.order('created_at DESC')
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def require_signin
    unless signed_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to signin_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user
      redirect_to posts_path
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out @user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Account created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :remember_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
      @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def sign_out(user)
    session.delete(:user_id)
    cookies.delete(:remember_token)
    current_user=(nil)
    redirect_to root_path
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">ClubHouse</a>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Posts", posts_path %></li>
				<% if signed_in? %>
					<li><%= link_to "Create Post", new_post_path %></li>
					<li><%= link_to "Sign Out", signout_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign In", signin_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Montserrat:400,700', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts">
  <div class="container">
    <div class="jumbotron">
      <h1>Find all the <b>embarassing</b> stories by other ClubHouse members here.</h1>
      <%= link_to "Create your own post »", new_post_path, class: "btn btn-primary" %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <% @posts.each do |post| %>
        <br>
          <div class="background">
            <div class="border">
            <h2><%= post.title %></h2>
            <p>by: <%= signed_in? ? post.user.name : "Sign in to see the author" %> at <%= post.created_at %></p>
            </div>
            <p><%= post.body %></p>
          </div>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Create new post</h1>
    <div class="container-main">
      <div class="form-group">
        <%= form_for @post do |f| %>
        <%= render 'shared/error_messages' %>

          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>

          <%= f.label :body %>
          <%= f.text_area :body, size: "60x12", class: "form-control" %>
          <br>
          <%= f.submit "Create post »", class: "btn btn-primary" %>

          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>. Please rectify and try again.
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/shared/_user_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>. Please rectify and try again.
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to the ClubHouse</h1>
      <p>View embarassing posts by unknown authors, or join to post your own and see who could be talking about you ;)</p>

        <%= link_to "Sign up now »", signup_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<section class="call-to-action">
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<span class="glyphicon glyphicon-pencil glyphicon-large" aria-hidden="true"></span>
			<h3>Spill Secrets</h3>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
		</div>
		<div class="col-md-4">
			<span class="glyphicon glyphicon-eye-open glyphicon-large" aria-hidden="true"></span>
			<h3>See who's posting</h3>
			<p>Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. Lorem ipsum dolor.</p>
		</div>
		<div class="col-md-4">
			<span class="glyphicon glyphicon-sunglasses glyphicon-large" aria-hidden="true"></span>
			<h3>Anonymous to outside users</h3>
			<p>Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
		</div>
	</div>
</div>
</section>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Sign up</h1>
    <div class="container-main">
      <div class="form-group">
        <%= form_for(@user, url: signup_path) do |f| %>
          <%= render 'shared/user_error_messages' %>

          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
          <br>

          <%= f.label :email %>
          <%= f.email_field :email, class: "form-control" %>
          <br>

          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
          <br>

          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
          <br>
          <br>
          <%= f.submit "Create account »", class: "btn btn-primary" %>

          <% end %>
        </div>
      </div>
    </div>
</div>